# include <string>
# include <vector>
#include <iostream>
#ifndef EJERCICIOS_H
#define EJERCICIOS_H

class Ejercicios {
    private:
        void imprimirLaberinto(const std::vector<std::vector<int>>& laberinto);
        int insertaEnEnteroCreciente(int x, int a);
        int elementoEnPosicion(const std::vector<int>& a, int inf, int sup);
        void imprimirSolucion(const std::vector<bool>& solucion, const std::vector<int>& L);
        int buscaSubconjunto(int i, int suma_parcial, const std::vector<int>& L, int s,
            std::vector<bool>& sol_parcial, std::vector<bool>& sol_opt,
            int card_opt, int card);
        int calcularTMejorCaso(int n);
        int calcularTPeorCaso(int n);
        bool esta_ordenada_matriz(const std::vector<std::vector<int>>& A, int inicio_fila, int fin_fila, int inicio_col, int fin_col);
        bool es_candidato_valido(int k, int i, const std::vector<int>& sol, const std::vector<std::vector<int>>& A);
        bool colorear_backtracking(int i, int m, std::vector<int>& sol, const std::vector<std::vector<int>>& A);
        bool puede_colorear(const std::vector<std::vector<int>>& A, int m);
        std::pair<std::vector<double>, std::vector<double>> extrae_indices_pares_impares(const std::vector<double>& a);
        double evalua_polinomio(const std::vector<double>& c, double x);
        int genera_permutaciones_repeticion(int i, std::vector<std::string>& sol, std::vector<int>& r, const std::vector<std::string>& a);
        int factorial(int n);
    public:
        Ejercicios();
        void ex_pag6();
        void ex_pag7();
        void ex_pag8();
        void ex_pag10();
        void ex_pag11();
        void ex_pag12();
        void ex_pag15();
        void ex_pag16();
        void ex_pag17();
        void ex_pag18();
        void ex_pag20();
        void ex_pag21_2();
        void ex_pag21_3();
        void ex_pag22();
        void ex_pag25_1();
        void ex_pag25_2();
        void ex_pag27();
        void ex_pag28();
        void ex_pag29();
        void ex_pag32();
        void ex_pag37();
        void ex_pag38();
        void ex_pag39();
        void ex_pag40();
        void ex_pag41();
        void ex_pag42();
        void ex_pag45();
        void ex_pag46();
        void ex_pag47();
        void ex_pag48();
        void ex_pag49();
        void ex_pag51();
        void ex_pag52();
        void ex_pag53();
        void ex_pag56();
        void ex_pag58();
        void ex_pag59();
        void ex_pag62();
        void ex_pag63();
        void ex_pag65();
        void ex_pag68();
        void ex_pag69();
        void ex_pag70();
        void ex_pag71();
        void ex_pag73();
        void ex_pag74();
        void ex_pag76();
        void ex_pag78();
        void ex_pag81();
        void ex_pag82();
        void ex_pag83();
        void ex_pag85();
        void ex_pag89_1();
        void ex_pag89_2();
        void ex_pag90();
        void ex_pag92_1();
        void ex_pag92_2();
        void ex_pag93_3();
        void ex_pag93_4();
        void ex_pag95_1();
        void ex_pag95_2();
        void ex_pag95_3();
        void ex_pag97_1();
        void ex_pag97_2();
        void ex_pag97_3();
        void ex_pag99_1();
        void ex_pag99_2();
        void ex_pag99_3();
        void ex_pag99_4();
        void ex_pag101_1();
        void ex_pag101_2();
        void ex_pag101_3();
        void ex_pag103_1();
        void ex_pag103_2();
        void ex_pag103_3();
        void ex_pag105_1();
        void ex_pag105_2();
        void ex_pag105_3();
        void ex_pag107();
        void ex_pag108();
        void ex_pag110_1();
        void ex_pag110_2();
        void ex_pag110_3();
        void ex_pag110_4();
        void ex_pag110_5();
        void ex_pag110_6();
        void ex_pag110_7();
        void ex_pag110_8();
        void ex_pag111_9();
        void ex_pag111_10();
        void ex_pag112_11();
        void ex_pag112_12();
        void ex_pag112_13();
        void ex_pag112_14();
        void ex_pag112_15();
        void ex_pag113_16();
        void ex_pag113_17();
        void ex_pag113_18();
        void ex_pag114();
        void ex_pag115();
        void ex_pag116();
        void ex_pag117();
        void ex_pag118();
        void ex_pag120_6();
        void ex_pag120_7();
        void ex_pag121();
        void ex_pag123();
        void ex_pag125();
        void ex_pag127();
        void ex_pag129();
        void ex_pag132();
        void ex_pag136();
        void ex_pag138();
        void ex_pag139_1();
        void ex_pag139_2();
        void ex_pag139_3();
        void ex_pag139_4();
        void ex_pag139_5();
        void ex_pag139_6();
        void ex_pag139_7();
        void ex_pag140();
        void ex_pag141_9();
        void ex_pag141_10();
        void ex_pag141_11();
        void ex_pag141_12();
        void ex_pag142_13();
        void ex_pag142_14();
        void ex_pag143_15();
        void ex_pag143_16();
        void ex_pag144_1();
        void ex_pag144_2();
        void ex_pag144_3();
        void ex_pag144_4();
        void ex_pag145_5();
        void ex_pag145_6();
        void ex_pag145_7();
        void ex_pag145_8();
        void ex_pag145_9();
        void ex_pag145_10();
        void ex_pag145_11();
        void ex_pag145_12();
        void ex_pag146_13();
        void ex_pag146_14();
        void ex_pag146_15();
        void ex_pag146_16();
        void ex_pag147();
        void ex_pag148_1();
        void ex_pag148_2();
        void ex_pag148_3();
        void ex_pag148_4();
        void ex_pag149_5();
        void ex_pag149_6();
        void ex_pag149_7();
        void ex_pag149_8();
        void ex_pag150();
        void ex_pag151_1();
        void ex_pag151_2();
        void ex_pag151_3();
        void ex_pag151_4();
        void ex_pag151_5();
        void ex_pag151_6();
        void ex_pag152_7();
        void ex_pag152_8();
        void ex_pag153_1();
        void ex_pag153_2();
        void ex_pag154_3();
        void ex_pag154_4();
        void ex_pag155_5();
        void ex_pag155_6();
        void ex_pag156_7();
        void ex_pag156_8();
        void ex_pag157_1();
        void ex_pag157_2();
        void ex_pag158_3();
        void ex_pag158_4();
        void ex_pag159_5();
        void ex_pag159_6();
        void ex_pag159_7();
        void ex_pag159_8();
        void ex_pag159_9();
        void ex_pag160_1();
        void ex_pag160_2();
        void ex_pag160_3();
        void ex_pag160_4();
        void ex_pag161_5();
        void ex_pag161_6();
        void ex_pag161_7();
        void ex_pag161_8();
};

#endif // ex_pagS_H